name: Bug report
description: File a bug report
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect?
      placeholder: A clear and concise description of the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior
      placeholder: 1. Go to '...'
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Project version (from `russian version` or `__version__`)
  - type: textarea
    id: logs
    attributes:
      label: Logs/Traceback
      render: shell

